HRM/Controllers/Level1Controller.cs
using HRM.Core;
using HRM.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace HRM.Controllers
{
    public class Level1Controller : Controller
    {

            // GET: Level1
            public ActionResult Level1Manage()
            {
                return View();
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="LSModel"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult LoadData(Level1Models LSModel)
        {
            GenericService act = new GenericService();
            SqlParameter[] parameters =
            {
                new SqlParameter("@Activity","GetData")
            };
            DataSet ds = act.Generic("LS_SPLevel1", parameters);

            var Object = ConvertDataTableToJSON(ds.Tables[0]);        

         
            return this.Json(Object, JsonRequestBehavior.AllowGet);
        }

        private static object ConvertDataTableToJSON(DataTable dt)
        {
            JavaScriptSerializer jSonString = new JavaScriptSerializer();
            List<Dictionary<string, object>> rows = new List<Dictionary<string, object>>();
            Dictionary<string, object> row;
            foreach (DataRow dr in dt.Rows)
            {
                row = new Dictionary<string, object>();
                foreach (DataColumn col in dt.Columns)
                {
                    row.Add(col.ColumnName, dr[col]);
                }
                rows.Add(row);
            }
            string serialize = jSonString.Serialize(rows);
            var data = jSonString.Deserialize<IEnumerable<object>>(serialize);
            return data;

        }   
    }
}

HRM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Datatable/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HRM", "GetAllEmp", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employee", "GetAllEmp", "Employee")</li>
                    <li>@Html.ActionLink("Company", "GetAllCompany", "Company")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Level</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="@Url.Action("Level1Manage","Level1")">Level1</a></li>        
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/Datatable/jquery.dataTables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>